// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: item.proto

package items

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ItemCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID string `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
}

func (x *ItemCodeRequest) Reset() {
	*x = ItemCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCodeRequest) ProtoMessage() {}

func (x *ItemCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCodeRequest.ProtoReflect.Descriptor instead.
func (*ItemCodeRequest) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemCodeRequest) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

type ItemCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ItemCodeResponse) Reset() {
	*x = ItemCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCodeResponse) ProtoMessage() {}

func (x *ItemCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCodeResponse.ProtoReflect.Descriptor instead.
func (*ItemCodeResponse) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_item_proto protoreflect.FileDescriptor

var file_item_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0f,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32,
	0x47, 0x0a, 0x0f, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData = file_item_proto_rawDesc
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_item_proto_rawDescData)
	})
	return file_item_proto_rawDescData
}

var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_item_proto_goTypes = []interface{}{
	(*ItemCodeRequest)(nil),  // 0: ItemCodeRequest
	(*ItemCodeResponse)(nil), // 1: ItemCodeResponse
}
var file_item_proto_depIdxs = []int32{
	0, // 0: ItemCodeService.GetItemCode:input_type -> ItemCodeRequest
	1, // 1: ItemCodeService.GetItemCode:output_type -> ItemCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_rawDesc = nil
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ItemCodeServiceClient is the client API for ItemCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemCodeServiceClient interface {
	GetItemCode(ctx context.Context, in *ItemCodeRequest, opts ...grpc.CallOption) (*ItemCodeResponse, error)
}

type itemCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemCodeServiceClient(cc grpc.ClientConnInterface) ItemCodeServiceClient {
	return &itemCodeServiceClient{cc}
}

func (c *itemCodeServiceClient) GetItemCode(ctx context.Context, in *ItemCodeRequest, opts ...grpc.CallOption) (*ItemCodeResponse, error) {
	out := new(ItemCodeResponse)
	err := c.cc.Invoke(ctx, "/ItemCodeService/GetItemCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemCodeServiceServer is the server API for ItemCodeService service.
type ItemCodeServiceServer interface {
	GetItemCode(context.Context, *ItemCodeRequest) (*ItemCodeResponse, error)
}

// UnimplementedItemCodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemCodeServiceServer struct {
}

func (*UnimplementedItemCodeServiceServer) GetItemCode(context.Context, *ItemCodeRequest) (*ItemCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemCode not implemented")
}

func RegisterItemCodeServiceServer(s *grpc.Server, srv ItemCodeServiceServer) {
	s.RegisterService(&_ItemCodeService_serviceDesc, srv)
}

func _ItemCodeService_GetItemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemCodeServiceServer).GetItemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ItemCodeService/GetItemCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemCodeServiceServer).GetItemCode(ctx, req.(*ItemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemCodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ItemCodeService",
	HandlerType: (*ItemCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemCode",
			Handler:    _ItemCodeService_GetItemCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
